blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('articles/<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('create/', views.create_view, name='create'),
	path('articles/<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
	path('articles/<int:pk>/edit/', views.edit_view, name='edit'),
	path('<int:pk>/comment/', views.post_comment, name='post_comment'),
	path('tags/<int:pk>/', views.tag_view, name='tag'),
	path('create_article/', views.create_article, name='create_article'),
	path('articles/<int:pk>/edit_article/', views.edit_article, name='edit_article'),
	path('tags/', views.TagListView.as_view(), name='tag_list')
]

simpleblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('blog.urls')),
	path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.title

	def tag_list(self):
		return ', '.join([tagging.tag.name for tagging in self.tagging_set.all()])

class Comment(models.Model):
	author = models.CharField(max_length=30)
	body = models.TextField()
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	posted_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.author

class Tag(models.Model):
	name = models.CharField(max_length=20)

	def __str__(self):
		return self.name

class Tagging(models.Model):
	tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
	article = models.ForeignKey(Article, on_delete=models.CASCADE)

	def __str__(self):
		return "tag=%s - article=%s" % (self.tag, self.article)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect

from .models import *

def custom_filter():
	return Article.objects.filter(pub_date__lte=timezone.now())

class IndexView(ListView):
	template_name = 'blog/index.html'
	context_object_name = 'article_list'

	def get_queryset(self):
		return custom_filter().order_by('-pub_date')

class TagListView(ListView):
	template_name = 'blog/tag_list.html'
	context_object_name = 'tag_list'

	def get_queryset(self):
		return Tag.objects.all()

class DetailView(DetailView):
	template_name = 'blog/detail.html'
	model = Article

	def get_queryset(self):
		return custom_filter()

class DeleteView(DeleteView):
	template_name = 'blog/delete.html'
	model = Article
	success_url = reverse_lazy('blog:index')

	def get_queryset(self):
		return custom_filter()

class EditView(UpdateView):
	template_name = 'blog/create.html'
	model = Article
	fields = ['title', 'body']

	def get_success_url(self):
		return reverse('blog:detail', args=(self.object.pk,))

	def get_queryset(self):
		return custom_filter()

def post_comment(request, pk):
	author = request.POST['author']
	body = request.POST['body']
	article = get_object_or_404(Article, pk=pk)

	comment = Comment.objects.create(author=author, body=body, article=article)
	comment.save()

	return HttpResponseRedirect(reverse('blog:detail', args=(pk,)))

def tag_view(request, pk):
	tag = get_object_or_404(Tag, pk=pk)
	context = {
		'tag': tag,
	}
	return render(request, 'blog/tag.html', context)

def create_view(request):
	return render(request, 'blog/create.html')

def edit_view(request, pk):
	return render(request, 'blog/create.html', {'article': Article.objects.get(pk=pk),})

def create_article(request):
	title = request.POST['title']
	body = request.POST['body']
	tags = request.POST['tags'].split(', ')

	article = Article.objects.create(title=title, body=body, pub_date=timezone.now())
	article.save()
	for t in tags:
		tag = None
		if t in [n.name for n in Tag.objects.all()]:
			tag = Tag.objects.get(name=t)
		else:
			tag = Tag.objects.create(name=t)
			tag.save()
		Tagging.objects.create(tag=tag, article=article).save()

	return HttpResponseRedirect(reverse('blog:detail', args=(article.pk,)))

def edit_article(request, pk):
	title = request.POST['title']
	body = request.POST['body']
	tags = request.POST['tags'].split(', ')
	article = Article.objects.get(pk=pk)
	taggings = article.tag_list().split(', ')
	full_tag_list = [t.name for t in Tag.objects.all()]

	article.title = title
	article.body = body
	article.save()

	for t in tags:
		if t not in full_tag_list:
			tag = Tag.objects.create(name=t)
			tag.save()
			Tagging.objects.create(tag=tag, article=article).save()
		elif t not in taggings:
			tag = Tag.objects.get(name=t)
			Tagging.objects.create(tag=tag, article=article).save()

	for t in taggings:
		if t not in tags:
			tag = Tag.objects.get(name=t)
			tagging = Tagging.objects.get(tag=tag, article=article)
			tagging.delete()

	return HttpResponseRedirect(reverse('blog:detail', args=(article.pk,)))

blog/templates/blog/create.html
<link href="http://tutorials.jumpstartlab.com/assets/blogger/screen.css" rel="stylesheet" type="text/css">

{% if article %}
<form method='post' action="{% url 'blog:edit_article' article.pk %}">
{% else %}
<form method='post' action="{% url 'blog:create_article' %}">
{% endif %}
{% csrf_token %}
	<p>
		<label for="id_title">TITLE:</label>
		<input type="text" name="title" value="{{article.title}}" maxlength="200" id="id_title" required>
	</p>
	<p>
		<label for="id_body">BODY:</label>
		<textarea name="body" cols="40" rows="10" id="id_body" required>{{article.body}}</textarea>
	</p>
	<p>
		<label for="id_tags">TAGS:</label>
		<input type="text" name="tags" value="{{article.tag_list}}" id="id_tags">
	</p>
	<input type='submit' value='Submit'>
</form>

{% if article %}
<a href="{% url 'blog:detail' article.pk %}">Nevermind</a>
{% else %}
<a href="{% url 'blog:index' %}">Back to article list</a>
{% endif %}

blog/templates/blog/delete.html
<link href="http://tutorials.jumpstartlab.com/assets/blogger/screen.css" rel="stylesheet" type="text/css">

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

<a href="{% url 'blog:detail' object.pk %}">Nevermind</a>

blog/templates/blog/detail.html
{% load humanize %}

<link href="http://tutorials.jumpstartlab.com/assets/blogger/screen.css" rel="stylesheet" type="text/css">

<h1>{{ article.title }}</h1>
<h2>Posted on {{ article.pub_date }}</h2>
<p>
	Tags:
	{% for tagging in article.tagging_set.all %}
	<a href="{% url 'blog:tag' tagging.tag.pk %}">{{ tagging.tag }}</a>
	{% endfor %}
</p>
<p>{{ article.body }}</p>

<h3>Comments ({{ article.comment_set.count }})</h3>
{% for comment in article.comment_set.all %}
	<div>
		<h4>Comment by {{ comment.author }}</h4>
		<p>Posted {{ comment.posted_at|naturaltime }}</p>
		<p class="comment">{{ comment.body }}</p>
	</div>
{% endfor %}

<h3>Post a Comment</h3>
{% if error_message %}
<p>*{{ error_message }}*</p>
{% endif %}
<form method="post" action="{% url 'blog:post_comment' article.pk %}">
	{% csrf_token %}
	<label for="author">User</label>
	<input type="text" name="author" value="{{author}}" required>
	<label for="body">Comment</label>
	<input type="text" name="body" value="{{body}}" required>
	<input type="submit" value="Submit">
</form>

<a href="{% url 'blog:edit' article.pk %}">Edit article</a>
<a href="{% url 'blog:delete' article.pk %}">Delete article</a>
<a href="{% url 'blog:index' %}">Back to article list</a>

blog/templates/blog/index.html
<link href="http://tutorials.jumpstartlab.com/assets/blogger/screen.css" rel="stylesheet" type="text/css">

<h1>All Articles</h1>

{% if article_list %}
<ul>
	{% for article in article_list %}
	<li>
		<a class='article_title' id='article_{{ article.pk }}' href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
	</li>
	{% endfor %}
</ul>

{% else %}
<h2>No articles are available.</h2>
{% endif %}

<a class="new_article" href="{% url 'blog:create' %}">Create a new article</a>

blog/templates/blog/tag.html
<link href="http://tutorials.jumpstartlab.com/assets/blogger/screen.css" rel="stylesheet" type="text/css">

<h1>Articles with tag: {{ tag.name }}</h1>

<div>
{% for tagging in tag.tagging_set.all %}
<a href="{% url 'blog:detail' tagging.article.pk %}">{{ tagging.article }}</a>
{% endfor %}
</div>

<a href="{% url 'blog:index' %}">Back to article list</a>
<a href="{% url 'blog:tag_list' %}">Full tag list</a>

blog/templates/blog/tag_list.html
<link href="http://tutorials.jumpstartlab.com/assets/blogger/screen.css" rel="stylesheet" type="text/css">

<h1>All Tags</h1>

{% if tag_list %}
<ul>
	{% for tag in tag_list %}
	<li>
		<a class='article_title' href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
	</li>
	{% endfor %}
</ul>

{% else %}
<h2>No tags have been made.</h2>
{% endif %}

<a class="new_article" href="{% url 'blog:index' %}">Article List</a>